"""Add lockout fields, updated_at columns, review unique constraint, check constraints

Revision ID: 063b1e814d29
Revises: 
Create Date: 2026-02-11 15:11:41.035850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063b1e814d29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_name', ['name'], unique=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_review_user_product_order', ['user_id', 'product_id', 'order_id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_user_product_order', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_name')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
