"""Add sort_order to LagerCategory

Revision ID: 60e566167327
Revises: 2957303da96e
Create Date: 2025-10-03 19:28:16.889262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e566167327'
down_revision = '2957303da96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lager_category', schema=None) as batch_op:
        # Zamijenite originalnu liniju sa ovom ispod
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lager_category', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
