"""Add availability to product

Revision ID: 948fcd17c1dc
Revises: ecd042c38e19
Create Date: 2025-09-29 23:30:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948fcd17c1dc'
down_revision = 'ecd042c38e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))

    # Manually update existing rows to have a default value
    op.execute("UPDATE product SET availability = 'Dostupno odmah' WHERE availability IS NULL")

    # Now, alter the column to be NOT NULL
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('availability')
    # ### end Alembic commands ###