"""Add extended_warranty to order_items table

Revision ID: e0f942a3b88b
Revises: 60e566167327
Create Date: 2025-11-14 14:56:50.244115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f942a3b88b'
down_revision = '60e566167327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_warranty', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('extended_warranty')

    # ### end Alembic commands ###
