"""Add product condition and extended warranty to cart

Revision ID: ecd042c38e19
Revises: 92f70bfb9410
Create Date: 2025-09-28 18:48:53.364239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd042c38e19'
down_revision = '92f70bfb9410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_warranty', sa.Boolean(), server_default=sa.false(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=20), server_default='Novo', nullable=True))

    # Postavljanje default vrijednosti za postojeće redove
    op.execute("UPDATE cart_item SET extended_warranty = 0 WHERE extended_warranty IS NULL")
    op.execute("UPDATE product SET condition = 'Novo' WHERE condition IS NULL")

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('extended_warranty', existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('condition', existing_type=sa.VARCHAR(length=20), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('condition')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('extended_warranty')
    # ### end Alembic commands ###